language: node_js
node_js: node

services:
  -progresql

env:
    TEST_DATABASE_URL: postgres://postgres@localhost/noteful-test
before_script:
    - psql -c 'CREATE DATABASE "noteful-test";' -U postgres